version: '3.8'

services:
  app:
    build:
      context: .
    container_name: siom-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=siom_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    expose:
      - 9000 # Port internal untuk PHP-FPM

  nginx:
    image: nginx:stable
    container_name: siom-nginx
    depends_on:
      - app
    ports:
      - "80:80"     # untuk HTTP
      - "443:443"   # untuk HTTPS
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs          # Sertifikat SSL
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: siom-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: siom_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: siom-pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysqldata:
